filebeat.inputs:
  - type: log
    enabled: true
    # 开启json解析
    json.keys_under_root: true
    json.add_error_key: true
    # 日志文件路径
    paths:
      - /usr/share/filebeat/docker/logs/*.log

setup.template.settings:
  index.number_of_shards: 1

fields:
  service: brush-api

# setup filebeat to send output to logstash
output.logstash:
  hosts: ["10.10.1.14:5044"]

# ================================= Processors =================================
processors:
  - decode_json_fields:
      fields: ['@timestamp','level','content','trace','span','duration']
      target: ""
  - drop_fields:    #删除字段，不再kibana里面展示，默认情况kibana里面会自动展示这些beat字段
      fields: ["beat"]